### ISSUE TITLE
Tests fail under Debian Bookworm with Rakudo 2022.07.

### ISSUE THREAD

**Issue by vadz** [retupmoca/P6-LibraryMake#37]
This module is getting installed as a dependency when running `zef install --install-to=home LibXML` but fails with:

```
===> Testing: LibraryMake:ver<1.0.0>
[LibraryMake] /usr/bin/ld: cannot find -ltommath: No such file or directory
[LibraryMake] /usr/bin/ld: cannot find -luv: No such file or directory
[LibraryMake] collect2: error: ld returned 1 exit status
[LibraryMake] make: *** [Makefile:4: test] Error 1
[LibraryMake] The spawned command 'make' exited unsuccessfully (exit code: 2, signal: 0)
[LibraryMake]   in block <unit> at t/01-basic.t line 21
[LibraryMake] # You planned 8 tests, but ran 5
===> Testing [FAIL]: LibraryMake:ver<1.0.0>
Aborting due to test failure: LibraryMake:ver<1.0.0> (use --force-test to override)
```

Do I really have to install libtommath-dev and libuv-dev (the non-dev packages are already installed) just to be able to install it?

**Comment by JJ** [comment]
If I remember correctly, wouldn't those libraries be part of MoarVM? Why would we need to install them here?

**Comment by vadz** [comment]
Not sure if this question was for me, but if it was, then I can't answer it, unfortunately. But at least under Debian Rakudo doesn't have the dependencies on libtommath-dev and libuv-dev packages, so they're not necessarily installed (even though the packages without "-dev" suffix are).

**Comment by JJ** [comment]
> Not sure if this question was for me, but if it was, then I can't answer it, unfortunately. But at least under Debian Rakudo doesn't have the dependencies on libtommath-dev and libuv-dev packages, so they're not necessarily installed (even though the packages without "-dev" suffix are).

Yes, it was. Can you please check if it's still happening or it's a flapper? If the former, I think that the only way to "fix" it is to try and create a GitHub action in a Docker container that tests everything in Debian, and provide (possibly) documentation to carry out the installation, if those are effectively requirements for *this* specific module to work.

**Comment by vadz** [comment]
Sorry, I'm totally lost. The way to fix this seems obvious to me: skip this test if the libraries are not available. Am I missing something here?

And of course it's not a flapper, it tries to link with the libraries that are simply not present, how could this ever work.

**Comment by JJ** [comment]
Skipping would not really fix it, it would sweep it under the rug. My point is that there's nothing in this module that requires those specific libraries. My hunch here is that somehow it's using pre-defined `LDLIBS` or maybe `LDFLAGS` environment variables. If that proves correct, we should probably try and make some verifications before line 21, where it errors, either in the test or in the code itself.
It would *really* help if you cloned the repo now and tested it. If it still fails, please look for `shell(%vars<MAKE>);` in `t/01-basic.t` (not any more in line 21) and insert a `say %vars` in the line before that one; issue a `raku -I. t/01-basic.t` and paste the error output if it fails. Thanks!

**Comment by vadz** [comment]
Sorry for a stupid question, but how am I supposed to test it? Running the command from GitHub CI workflow results in another, apparently unrelated, failure:
```console
% zef --verbose install .
===> Testing: LibraryMake:ver<1.0.1>:auth<zef:jjmerelo>
[LibraryMake] t/01-basic.t .. All 3 subtests passed 
[LibraryMake] All tests successful.
[LibraryMake] 
[LibraryMake] Test Summary Report
[LibraryMake] -------------------
[LibraryMake] t/01-basic.t (Wstat: 0 Tests: 3 Failed: 0)
[LibraryMake]   Parse errors: Subtest 2 expected 5 but contains 3 tests
[LibraryMake] Files=1, Tests=3,  0 wallclock secs
[LibraryMake] Result: FAILED
===> Testing [FAIL]: LibraryMake:ver<1.0.1>:auth<zef:jjmerelo>
Aborting due to test failure: LibraryMake:ver<1.0.1>:auth<zef:jjmerelo> (use --force-test to override)
```

**Comment by JJ** [comment]
That probably proves that the environment variables that were causing the error were in a specific environment, and not in this workflow.
Also, that problem was already fixed, [at least in Ubuntu](https://github.com/retupmoca/P6-LibraryMake/actions/runs/6479584074/job/17593400517).
Directly answering your question, do you have the original Debian machine handy, or some other like that? Clone the repo, install latest version of Raku, and run that same command, `zef --verbose install .`

If you forked this repo and got that error, please let me know and give me a link, I'll try and see what could be the problem there; opening an issue with the whole context would also help.

**Comment by vadz** [comment]
> That probably proves that the environment variables that were causing the error were in a specific environment, and not in this workflow.

Can it be something in LibXML then? Because I definitely don't (and didn't) have anything like this in my environment. I can still reproduce the original problem with `zef install LibXML` but I don't know how to tell it to use the latest version of LibraryMake instead of v1.0.0.

> Also, that problem was already fixed, [at least in Ubuntu](https://github.com/retupmoca/P6-LibraryMake/actions/runs/6479584074/job/17593400517).

Sorry, I'm seeing the problem with the same d7aa5627f00f400518b011423c2dc7d5e2c64c55 as is tested there so it's definitely not fixed for me. Could it be a raku version difference? Mine is

```console
% raku --version
Welcome to Rakudo™ v2022.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.12.
```

**Comment by JJ** [comment]
> > That probably proves that the environment variables that were causing the error were in a specific environment, and not in this workflow.
> 
> Can it be something in LibXML then? Because I definitely don't (and didn't) have anything like this in my environment. I can still reproduce the original problem with `zef install LibXML` but I don't know how to tell it to use the latest version of LibraryMake instead of v1.0.0.

Um, could be. Let me check that one. Thanks!
> 
> > Also, that problem was already fixed, [at least in Ubuntu](https://github.com/retupmoca/P6-LibraryMake/actions/runs/6479584074/job/17593400517).
> 
> Sorry, I'm seeing the problem with the same [d7aa562](https://github.com/retupmoca/P6-LibraryMake/commit/d7aa5627f00f400518b011423c2dc7d5e2c64c55) as is tested there so it's definitely not fixed for me. Could it be a raku version difference? Mine is
> 
> ```
> % raku --version
> Welcome to Rakudo™ v2022.12.
> Implementing the Raku® Programming Language v6.d.
> Built on MoarVM version 2022.12.
> ```

Could very well be; these workflows use `latest` which is 2023.09 right now. Same I have locally, where it's not erroring either. However, it does not look like that should be the problem. If you open an issue, I'd be happy to help.

**Comment by vadz** [comment]
I'm closing this because I finally believe it's a [Debian package bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059502) and so not related to this module, sorry for erroneously opening it here originally.
